// AUTO-GENERATED by scripts/gen-meta.mjs — do not edit by hand.
// Rich per-component documentation (Props, Design Tokens, Accessibility, Usage).
// The component page renders any section that is present.

export type PropRow = {
  component: string
  prop: string
  type: string
  default: string
  description: string
}

export type TokenRow = {
  token: string
  value: string
  usage: string
  /** Render a live color swatch for `var(<token>)`. */
  swatch?: boolean
}

export type A11yRow = { keys: string; action: string }

export type ComponentMeta = {
  importCode?: string
  usageCode?: string
  props?: PropRow[]
  tokens?: TokenRow[]
  a11y?: A11yRow[]
  a11yNote?: string
  install?: string
  shadcnSlug?: string
  figmaNode?: string
}

const FIGMA_FILE =
  "https://www.figma.com/design/NN6Wp4Hgsug3OKhiQdL27d/-shadcn_ui-components-not-token--Fluke---Copy-"

export function figmaUrl(node?: string) {
  return node ? `${FIGMA_FILE}?node-id=${node}` : FIGMA_FILE
}

export function shadcnUrl(slug: string, meta?: ComponentMeta) {
  return `https://ui.shadcn.com/docs/components/${meta?.shadcnSlug ?? slug}`
}

export function installCmd(slug: string, meta?: ComponentMeta) {
  return meta?.install ?? `npx shadcn@latest add ${slug}`
}

export const componentMeta: Record<string, ComponentMeta> = {
  "accordion": {
    figmaNode: "72-2591",
    importCode: "import {\n  Accordion,\n  AccordionContent,\n  AccordionItem,\n  AccordionTrigger,\n} from \"@/components/ui/accordion\"",
    usageCode: "<Accordion type=\"single\" collapsible className=\"w-full\">\n  <AccordionItem value=\"item-1\">\n    <AccordionTrigger>Product Information</AccordionTrigger>\n    <AccordionContent>\n      Our flagship product combines cutting-edge technology.\n    </AccordionContent>\n  </AccordionItem>\n</Accordion>",
    props: [
      { component: "Accordion", prop: "type", type: "\"single\" | \"multiple\"", default: "—", description: "Single or multiple open items." },
      { component: "Accordion", prop: "collapsible", type: "boolean", default: "false", description: "Allow closing when type=\"single\"." },
      { component: "Accordion", prop: "defaultValue", type: "string | string[]", default: "—", description: "Default open item(s) — uncontrolled." },
      { component: "AccordionItem", prop: "value", type: "string", default: "—", description: "Unique identifier for this item." },
      { component: "AccordionItem", prop: "disabled", type: "boolean", default: "false", description: "Prevents interaction." },
    ],
    tokens: [
      { token: "--border", value: "border-border", usage: "Item separator", swatch: true },
      { token: "--foreground", value: "text-foreground", usage: "Label + content text", swatch: true },
      { token: "--muted-foreground", value: "text-muted-foreground", usage: "Chevron icon", swatch: true },
      { token: "text-sm", value: "14px", usage: "Trigger + content size" },
      { token: "font-medium", value: "500", usage: "Trigger weight" },
    ],
    a11yNote: "Implements the WAI-ARIA Accordion pattern via Radix UI.",
    a11y: [
      { keys: "Enter / Space", action: "Toggle open" },
      { keys: "Tab", action: "Move to next focusable" },
    ],
  },
  "alert": {
    figmaNode: "72-2633",
    importCode: "import { Alert, AlertTitle, AlertDescription } from \"@/components/ui/alert\"",
    usageCode: "<Alert>\n  <Terminal />\n  <AlertTitle>Heads up!</AlertTitle>\n  <AlertDescription>You can add components to your app.</AlertDescription>\n</Alert>",
    props: [
      { component: "Alert", prop: "variant", type: "\"default\" | \"destructive\"", default: "\"default\"", description: "Visual tone of the callout." },
    ],
    tokens: [
      { token: "--card", value: "bg-card", usage: "Alert surface", swatch: true },
      { token: "--foreground", value: "text-foreground", usage: "Title text", swatch: true },
      { token: "--muted-foreground", value: "text-muted-foreground", usage: "Description text", swatch: true },
      { token: "--destructive", value: "text-destructive", usage: "Destructive variant", swatch: true },
    ],
    a11yNote: "Use role=\"alert\" only for time-sensitive messages; this is a static callout by default.",
  },
  "alert-dialog": {
    figmaNode: "72-2675",
    importCode: "import {\n  AlertDialog,\n  AlertDialogAction,\n  AlertDialogCancel,\n  AlertDialogContent,\n  AlertDialogDescription,\n  AlertDialogFooter,\n  AlertDialogHeader,\n  AlertDialogTitle,\n  AlertDialogTrigger,\n} from \"@/components/ui/alert-dialog\"",
    usageCode: "<AlertDialog>\n  <AlertDialogTrigger asChild>\n    <Button variant=\"outline\">Delete</Button>\n  </AlertDialogTrigger>\n  <AlertDialogContent>\n    <AlertDialogHeader>\n      <AlertDialogTitle>Are you sure?</AlertDialogTitle>\n      <AlertDialogDescription>This cannot be undone.</AlertDialogDescription>\n    </AlertDialogHeader>\n    <AlertDialogFooter>\n      <AlertDialogCancel>Cancel</AlertDialogCancel>\n      <AlertDialogAction>Continue</AlertDialogAction>\n    </AlertDialogFooter>\n  </AlertDialogContent>\n</AlertDialog>",
    props: [
      { component: "AlertDialog", prop: "open", type: "boolean", default: "—", description: "Controlled open state." },
      { component: "AlertDialog", prop: "onOpenChange", type: "(open: boolean) => void", default: "—", description: "Open-state change handler." },
      { component: "AlertDialogAction", prop: "asChild", type: "boolean", default: "false", description: "Merge props onto child." },
    ],
    tokens: [
      { token: "--card", value: "bg-card", usage: "Dialog surface", swatch: true },
      { token: "--foreground", value: "text-foreground", usage: "Title text", swatch: true },
      { token: "--muted-foreground", value: "text-muted-foreground", usage: "Description", swatch: true },
      { token: "--primary", value: "bg-primary", usage: "Action button", swatch: true },
    ],
    a11yNote: "A modal that interrupts and requires a choice; focus is trapped until dismissed.",
    a11y: [
      { keys: "Tab / Shift+Tab", action: "Cycle focus (trapped)" },
      { keys: "Esc", action: "Close" },
    ],
  },
  "aspect-ratio": {
    figmaNode: "1098-924",
    importCode: "import { AspectRatio } from \"@/components/ui/aspect-ratio\"",
    usageCode: "<AspectRatio ratio={16 / 9}>\n  <img src=\"/cover.jpg\" alt=\"Cover\" className=\"size-full object-cover\" />\n</AspectRatio>",
    props: [
      { component: "AspectRatio", prop: "ratio", type: "number", default: "1", description: "Width-to-height ratio, e.g. 16 / 9." },
    ],
    a11yNote: "Layout-only wrapper — it constrains dimensions and consumes no color tokens; styling comes from the child you place inside. Give media an alt attribute.",
  },
  "avatar": {
    figmaNode: "72-2717",
    importCode: "import { Avatar, AvatarImage, AvatarFallback } from \"@/components/ui/avatar\"",
    usageCode: "<Avatar>\n  <AvatarImage src=\"/user.png\" alt=\"@shadcn\" />\n  <AvatarFallback>CN</AvatarFallback>\n</Avatar>",
    props: [
      { component: "AvatarImage", prop: "src", type: "string", default: "—", description: "Image source." },
      { component: "AvatarImage", prop: "alt", type: "string", default: "—", description: "Alt text for the image." },
      { component: "AvatarFallback", prop: "delayMs", type: "number", default: "—", description: "Delay before showing the fallback." },
    ],
    tokens: [
      { token: "--muted", value: "bg-muted", usage: "Fallback background", swatch: true },
      { token: "--muted-foreground", value: "text-muted-foreground", usage: "Fallback initials", swatch: true },
      { token: "rounded-full", value: "9999px", usage: "Circular shape" },
    ],
    a11yNote: "Always provide AvatarFallback and an alt on AvatarImage.",
  },
  "badge": {
    figmaNode: "72-2718",
    importCode: "import { Badge } from \"@/components/ui/badge\"",
    usageCode: "<Badge>Default</Badge>\n<Badge variant=\"secondary\">Secondary</Badge>\n<Badge variant=\"outline\">Outline</Badge>\n<Badge variant=\"destructive\">Destructive</Badge>",
    props: [
      { component: "Badge", prop: "variant", type: "\"default\" | \"secondary\" | \"destructive\" | \"outline\"", default: "\"default\"", description: "Visual style." },
      { component: "Badge", prop: "asChild", type: "boolean", default: "false", description: "Render as the child element (e.g. a link)." },
    ],
    tokens: [
      { token: "--primary", value: "bg-primary", usage: "Default fill", swatch: true },
      { token: "--secondary", value: "bg-secondary", usage: "Secondary fill", swatch: true },
      { token: "--destructive", value: "bg-destructive", usage: "Destructive fill", swatch: true },
      { token: "rounded-md", value: "6px", usage: "Corner radius" },
    ],
    a11yNote: "Decorative status label — not focusable unless rendered asChild as a link.",
  },
  "breadcrumb": {
    figmaNode: "101-2",
    importCode: "import {\n  Breadcrumb,\n  BreadcrumbItem,\n  BreadcrumbLink,\n  BreadcrumbList,\n  BreadcrumbPage,\n  BreadcrumbSeparator,\n} from \"@/components/ui/breadcrumb\"",
    usageCode: "<Breadcrumb>\n  <BreadcrumbList>\n    <BreadcrumbItem>\n      <BreadcrumbLink href=\"/\">Home</BreadcrumbLink>\n    </BreadcrumbItem>\n    <BreadcrumbSeparator />\n    <BreadcrumbItem>\n      <BreadcrumbPage>Docs</BreadcrumbPage>\n    </BreadcrumbItem>\n  </BreadcrumbList>\n</Breadcrumb>",
    props: [
      { component: "BreadcrumbLink", prop: "asChild", type: "boolean", default: "false", description: "Render with a custom link (e.g. next/link)." },
    ],
    tokens: [
      { token: "--muted-foreground", value: "text-muted-foreground", usage: "Inactive crumbs", swatch: true },
      { token: "--foreground", value: "text-foreground", usage: "Current page", swatch: true },
    ],
    a11yNote: "Wrapped in nav aria-label=\"breadcrumb\"; the current page uses aria-current=\"page\".",
  },
  "button": {
    figmaNode: "72-2719",
    importCode: "import { Button } from \"@/components/ui/button\"",
    usageCode: "<Button>Save</Button>\n<Button variant=\"secondary\">Cancel</Button>\n<Button variant=\"outline\">View</Button>\n<Button variant=\"ghost\" size=\"icon\"><Settings /></Button>\n<Button variant=\"destructive\">Delete</Button>",
    props: [
      { component: "Button", prop: "variant", type: "\"default\" | \"secondary\" | \"outline\" | \"ghost\" | \"link\" | \"destructive\"", default: "\"default\"", description: "Visual style." },
      { component: "Button", prop: "size", type: "\"default\" | \"sm\" | \"lg\" | \"icon\"", default: "\"default\"", description: "Control size." },
      { component: "Button", prop: "asChild", type: "boolean", default: "false", description: "Render as the child (e.g. a link)." },
      { component: "Button", prop: "disabled", type: "boolean", default: "false", description: "Disable interaction." },
    ],
    tokens: [
      { token: "--primary", value: "bg-primary", usage: "Default fill", swatch: true },
      { token: "--primary-foreground", value: "text-primary-foreground", usage: "Label on primary", swatch: true },
      { token: "--ring", value: "ring-ring", usage: "Focus ring", swatch: true },
      { token: "h-9 px-4", value: "36 / 16px", usage: "Default size" },
    ],
    a11yNote: "Icon-only buttons need an aria-label.",
    a11y: [
      { keys: "Enter / Space", action: "Activate" },
      { keys: "Tab", action: "Move focus" },
    ],
  },
  "button-group": {
    figmaNode: "1185-1979",
    importCode: "import { ButtonGroup } from \"@/components/ui/button-group\"\nimport { Button } from \"@/components/ui/button\"",
    usageCode: "<ButtonGroup>\n  <Button variant=\"outline\">Bold</Button>\n  <Button variant=\"outline\">Italic</Button>\n  <Button variant=\"outline\">Underline</Button>\n</ButtonGroup>",
    props: [
      { component: "ButtonGroup", prop: "orientation", type: "\"horizontal\" | \"vertical\"", default: "\"horizontal\"", description: "Layout direction of the grouped buttons." },
    ],
    tokens: [
      { token: "--border", value: "border-border", usage: "Shared borders", swatch: true },
      { token: "rounded-md", value: "6px", usage: "Outer corner radius" },
    ],
    a11yNote: "Groups related buttons with shared borders; each button keeps its own focus.",
  },
  "calendar": {
    figmaNode: "72-2720",
    importCode: "import { Calendar } from \"@/components/ui/calendar\"",
    usageCode: "const [date, setDate] = React.useState<Date | undefined>(new Date())\n\n<Calendar mode=\"single\" selected={date} onSelect={setDate} className=\"rounded-md border\" />",
    props: [
      { component: "Calendar", prop: "mode", type: "\"single\" | \"multiple\" | \"range\"", default: "\"single\"", description: "Selection mode." },
      { component: "Calendar", prop: "selected", type: "Date | Date[] | DateRange", default: "—", description: "Selected date(s)." },
      { component: "Calendar", prop: "onSelect", type: "(date) => void", default: "—", description: "Selection handler." },
      { component: "Calendar", prop: "disabled", type: "Matcher | Matcher[]", default: "—", description: "Disabled days." },
    ],
    tokens: [
      { token: "--primary", value: "bg-primary", usage: "Selected day", swatch: true },
      { token: "--accent", value: "bg-accent", usage: "Hover / today", swatch: true },
      { token: "--muted-foreground", value: "text-muted-foreground", usage: "Outside days", swatch: true },
    ],
    a11yNote: "Built on React DayPicker with full keyboard grid navigation.",
    a11y: [
      { keys: "← / →", action: "Previous / next day" },
      { keys: "↑ / ↓", action: "Previous / next week" },
      { keys: "Home / End", action: "Start / end of week" },
      { keys: "PageUp / PageDown", action: "Previous / next month" },
    ],
  },
  "card": {
    figmaNode: "72-2721",
    importCode: "import {\n  Card,\n  CardHeader,\n  CardTitle,\n  CardDescription,\n  CardContent,\n  CardFooter,\n} from \"@/components/ui/card\"",
    usageCode: "<Card>\n  <CardHeader>\n    <CardTitle>Title</CardTitle>\n    <CardDescription>Description</CardDescription>\n  </CardHeader>\n  <CardContent>Content</CardContent>\n  <CardFooter>Footer</CardFooter>\n</Card>",
    props: [
      { component: "Card", prop: "className", type: "string", default: "—", description: "Surface container; compose the parts below inside it." },
      { component: "CardHeader", prop: "className", type: "string", default: "—", description: "Top section — holds CardTitle and CardDescription." },
      { component: "CardTitle", prop: "className", type: "string", default: "—", description: "Accessible heading for the card." },
      { component: "CardDescription", prop: "className", type: "string", default: "—", description: "Muted supporting text under the title." },
      { component: "CardContent", prop: "className", type: "string", default: "—", description: "Main body region." },
      { component: "CardFooter", prop: "className", type: "string", default: "—", description: "Bottom section — typically actions." },
    ],
    tokens: [
      { token: "--card", value: "bg-card", usage: "Surface", swatch: true },
      { token: "--card-foreground", value: "text-card-foreground", usage: "Text on card", swatch: true },
      { token: "--border", value: "border-border", usage: "Outline", swatch: true },
      { token: "p-6", value: "24px", usage: "Section padding" },
    ],
    a11yNote: "Layout container — do not nest a Card inside a Card.",
  },
  "carousel": {
    figmaNode: "72-2722",
    importCode: "import {\n  Carousel,\n  CarouselContent,\n  CarouselItem,\n  CarouselNext,\n  CarouselPrevious,\n} from \"@/components/ui/carousel\"",
    usageCode: "<Carousel className=\"w-full max-w-xs\">\n  <CarouselContent>\n    {items.map((i) => (\n      <CarouselItem key={i}>{i}</CarouselItem>\n    ))}\n  </CarouselContent>\n  <CarouselPrevious />\n  <CarouselNext />\n</Carousel>",
    props: [
      { component: "Carousel", prop: "orientation", type: "\"horizontal\" | \"vertical\"", default: "\"horizontal\"", description: "Scroll direction." },
      { component: "Carousel", prop: "opts", type: "EmblaOptionsType", default: "—", description: "Embla carousel options." },
    ],
    tokens: [
      { token: "--background", value: "bg-background", usage: "Control surface", swatch: true },
      { token: "--border", value: "border-border", usage: "Control outline", swatch: true },
    ],
    a11yNote: "Built on Embla; arrow controls expose aria-labels.",
    a11y: [
      { keys: "← / →", action: "Previous / next slide" },
      { keys: "Tab", action: "Reach prev/next controls" },
    ],
  },
  "chart": {
    figmaNode: "296-42",
    importCode: "import {\n  ChartContainer,\n  ChartTooltip,\n  ChartTooltipContent,\n} from \"@/components/ui/chart\"",
    usageCode: "<ChartContainer config={chartConfig} className=\"h-[200px] w-full\">\n  <BarChart data={data}>\n    <Bar dataKey=\"value\" fill=\"var(--chart-1)\" radius={4} />\n    <ChartTooltip content={<ChartTooltipContent />} />\n  </BarChart>\n</ChartContainer>",
    props: [
      { component: "ChartContainer", prop: "config", type: "ChartConfig", default: "—", description: "Maps data keys to label + color." },
    ],
    tokens: [
      { token: "--chart-1", value: "var(--chart-1)", usage: "Series 1", swatch: true },
      { token: "--chart-2", value: "var(--chart-2)", usage: "Series 2", swatch: true },
      { token: "--chart-3", value: "var(--chart-3)", usage: "Series 3", swatch: true },
      { token: "--chart-4", value: "var(--chart-4)", usage: "Series 4", swatch: true },
      { token: "--chart-5", value: "var(--chart-5)", usage: "Series 5", swatch: true },
    ],
    a11yNote: "Wraps Recharts; colors come from the --chart-* tokens for theme + dark support.",
  },
  "checkbox": {
    figmaNode: "72-2723",
    importCode: "import { Checkbox } from \"@/components/ui/checkbox\"\nimport { Label } from \"@/components/ui/label\"",
    usageCode: "<div className=\"flex items-center gap-2\">\n  <Checkbox id=\"terms\" />\n  <Label htmlFor=\"terms\">Accept terms</Label>\n</div>",
    props: [
      { component: "Checkbox", prop: "checked", type: "boolean | \"indeterminate\"", default: "—", description: "Controlled checked state." },
      { component: "Checkbox", prop: "onCheckedChange", type: "(checked) => void", default: "—", description: "Change handler." },
      { component: "Checkbox", prop: "disabled", type: "boolean", default: "false", description: "Disable the control." },
      { component: "Checkbox", prop: "aria-invalid", type: "boolean", default: "false", description: "Mark invalid for error styling." },
    ],
    tokens: [
      { token: "--primary", value: "bg-primary", usage: "Checked fill", swatch: true },
      { token: "--primary-foreground", value: "text-primary-foreground", usage: "Check mark", swatch: true },
      { token: "--input", value: "border-input", usage: "Unchecked border", swatch: true },
      { token: "--ring", value: "ring-ring", usage: "Focus ring", swatch: true },
    ],
    a11yNote: "Pair with a Label via htmlFor; compose with Field/FieldDescription for helper text.",
    a11y: [
      { keys: "Space", action: "Toggle checked" },
      { keys: "Tab", action: "Move focus" },
    ],
  },
  "collapsible": {
    figmaNode: "72-2724",
    importCode: "import {\n  Collapsible,\n  CollapsibleContent,\n  CollapsibleTrigger,\n} from \"@/components/ui/collapsible\"",
    usageCode: "<Collapsible>\n  <CollapsibleTrigger>Toggle</CollapsibleTrigger>\n  <CollapsibleContent>Hidden content</CollapsibleContent>\n</Collapsible>",
    props: [
      { component: "Collapsible", prop: "open", type: "boolean", default: "—", description: "Controlled open state." },
      { component: "Collapsible", prop: "defaultOpen", type: "boolean", default: "false", description: "Initial open state (uncontrolled)." },
      { component: "Collapsible", prop: "disabled", type: "boolean", default: "false", description: "Disable toggling." },
    ],
    tokens: [
      { token: "--foreground", value: "text-foreground", usage: "Trigger + content", swatch: true },
    ],
    a11yNote: "Single open/close disclosure; trigger exposes aria-expanded.",
    a11y: [
      { keys: "Enter / Space", action: "Toggle open" },
      { keys: "Tab", action: "Move to next focusable" },
    ],
  },
  "combobox": {
    figmaNode: "73-187",
    importCode: "import {\n  Combobox,\n  ComboboxInput,\n  ComboboxContent,\n  ComboboxList,\n  ComboboxItem,\n  ComboboxEmpty,\n} from \"@/components/ui/combobox\"",
    usageCode: "<Combobox items={frameworks}>\n  <ComboboxInput placeholder=\"Select a framework\" />\n  <ComboboxContent>\n    <ComboboxEmpty>No framework found.</ComboboxEmpty>\n    <ComboboxList>\n      {(item) => (\n        <ComboboxItem key={item} value={item}>{item}</ComboboxItem>\n      )}\n    </ComboboxList>\n  </ComboboxContent>\n</Combobox>",
    props: [
      { component: "Combobox", prop: "items", type: "T[]", default: "—", description: "The list of selectable items." },
      { component: "Combobox", prop: "multiple", type: "boolean", default: "false", description: "Allow multiple values (renders chips)." },
      { component: "Combobox", prop: "value / onValueChange", type: "T | T[] / fn", default: "—", description: "Controlled selection." },
      { component: "ComboboxInput", prop: "showClear", type: "boolean", default: "false", description: "Show a clear button." },
    ],
    tokens: [
      { token: "--popover", value: "bg-popover", usage: "Dropdown surface", swatch: true },
      { token: "--accent", value: "bg-accent", usage: "Highlighted option", swatch: true },
    ],
    a11yNote: "Built on the Base UI Combobox primitive (npx shadcn add combobox).",
    a11y: [
      { keys: "↑ / ↓", action: "Move between options" },
      { keys: "Enter / Space", action: "Select option" },
      { keys: "Esc", action: "Close" },
      { keys: "A–Z", action: "Type-ahead" },
    ],
  },
  "command": {
    figmaNode: "73-223",
    importCode: "import {\n  Command,\n  CommandEmpty,\n  CommandGroup,\n  CommandInput,\n  CommandItem,\n  CommandList,\n  CommandSeparator,\n} from \"@/components/ui/command\"",
    usageCode: "<Command className=\"rounded-lg border shadow-md\">\n  <CommandInput placeholder=\"Type a command…\" />\n  <CommandList>\n    <CommandEmpty>No results found.</CommandEmpty>\n    <CommandGroup heading=\"Suggestions\">\n      <CommandItem>Calendar</CommandItem>\n      <CommandItem>Search</CommandItem>\n    </CommandGroup>\n  </CommandList>\n</Command>",
    props: [
      { component: "CommandItem", prop: "onSelect", type: "(value: string) => void", default: "—", description: "Fires when the item is chosen." },
      { component: "CommandItem", prop: "disabled", type: "boolean", default: "false", description: "Disable the item." },
    ],
    tokens: [
      { token: "--popover", value: "bg-popover", usage: "Menu surface", swatch: true },
      { token: "--accent", value: "bg-accent", usage: "Active item", swatch: true },
      { token: "--muted-foreground", value: "text-muted-foreground", usage: "Group heading", swatch: true },
    ],
    a11yNote: "Built on cmdk with fuzzy search and full keyboard control.",
    a11y: [
      { keys: "↑ / ↓", action: "Move between options" },
      { keys: "Enter / Space", action: "Select option" },
      { keys: "Esc", action: "Close" },
      { keys: "A–Z", action: "Type-ahead" },
    ],
  },
  "context-menu": {
    figmaNode: "73-224",
    importCode: "import {\n  ContextMenu,\n  ContextMenuContent,\n  ContextMenuItem,\n  ContextMenuSeparator,\n  ContextMenuTrigger,\n} from \"@/components/ui/context-menu\"",
    usageCode: "<ContextMenu>\n  <ContextMenuTrigger>Right-click here</ContextMenuTrigger>\n  <ContextMenuContent>\n    <ContextMenuItem>Back</ContextMenuItem>\n    <ContextMenuSeparator />\n    <ContextMenuItem>Reload</ContextMenuItem>\n  </ContextMenuContent>\n</ContextMenu>",
    props: [
      { component: "ContextMenuItem", prop: "inset", type: "boolean", default: "false", description: "Indent to align with checkbox items." },
      { component: "ContextMenuItem", prop: "disabled", type: "boolean", default: "false", description: "Disable the item." },
    ],
    tokens: [
      { token: "--popover", value: "bg-popover", usage: "Menu surface", swatch: true },
      { token: "--accent", value: "bg-accent", usage: "Highlighted item", swatch: true },
    ],
    a11yNote: "Opens at the pointer on right-click / long-press.",
    a11y: [
      { keys: "↑ / ↓", action: "Move between items" },
      { keys: "→ / ←", action: "Open / close submenu" },
      { keys: "Enter / Space", action: "Select item" },
      { keys: "Esc", action: "Close menu" },
      { keys: "A–Z", action: "Type-ahead to item" },
    ],
  },
  "data-table": {
    figmaNode: "73-225",
    importCode: "import {\n  Table,\n  TableBody,\n  TableCell,\n  TableHead,\n  TableHeader,\n  TableRow,\n} from \"@/components/ui/table\"\nimport {\n  useReactTable,\n  getCoreRowModel,\n  flexRender,\n} from \"@tanstack/react-table\"",
    usageCode: "const table = useReactTable({ data, columns, getCoreRowModel: getCoreRowModel() })\n\n<Table>{/* render table.getHeaderGroups() and table.getRowModel().rows */}</Table>",
    props: [
      { component: "—", prop: "—", type: "—", default: "—", description: "Composed from Table + @tanstack/react-table." },
    ],
    tokens: [
      { token: "--border", value: "border-border", usage: "Row dividers", swatch: true },
      { token: "--muted", value: "bg-muted", usage: "Header / hover row", swatch: true },
    ],
    a11yNote: "A pattern, not a primitive: shadcn Table styling + TanStack Table for state.",
  },
  "date-picker": {
    figmaNode: "73-226",
    importCode: "import { Popover, PopoverContent, PopoverTrigger } from \"@/components/ui/popover\"\nimport { Calendar } from \"@/components/ui/calendar\"",
    usageCode: "<Popover>\n  <PopoverTrigger asChild>\n    <Button variant=\"outline\">{date ? format(date, \"PPP\") : \"Pick a date\"}</Button>\n  </PopoverTrigger>\n  <PopoverContent className=\"p-0\">\n    <Calendar mode=\"single\" selected={date} onSelect={setDate} />\n  </PopoverContent>\n</Popover>",
    props: [
      { component: "—", prop: "—", type: "—", default: "—", description: "Composed from Popover + Calendar." },
    ],
    tokens: [
      { token: "--popover", value: "bg-popover", usage: "Panel surface", swatch: true },
      { token: "--primary", value: "bg-primary", usage: "Selected day", swatch: true },
    ],
    a11yNote: "Calendar in a Popover. See Calendar for grid navigation keys.",
    a11y: [
      { keys: "Esc", action: "Close" },
      { keys: "Tab", action: "Move focus out" },
    ],
  },
  "dialog": {
    figmaNode: "73-227",
    importCode: "import {\n  Dialog,\n  DialogContent,\n  DialogDescription,\n  DialogFooter,\n  DialogHeader,\n  DialogTitle,\n  DialogTrigger,\n} from \"@/components/ui/dialog\"",
    usageCode: "<Dialog>\n  <DialogTrigger asChild>\n    <Button variant=\"outline\">Open</Button>\n  </DialogTrigger>\n  <DialogContent>\n    <DialogHeader>\n      <DialogTitle>Title</DialogTitle>\n      <DialogDescription>Description</DialogDescription>\n    </DialogHeader>\n  </DialogContent>\n</Dialog>",
    props: [
      { component: "Dialog", prop: "open", type: "boolean", default: "—", description: "Controlled open state." },
      { component: "Dialog", prop: "onOpenChange", type: "(open) => void", default: "—", description: "Open-state handler." },
      { component: "Dialog", prop: "modal", type: "boolean", default: "true", description: "Block interaction with the rest of the page." },
      { component: "DialogContent", prop: "showCloseButton", type: "boolean", default: "true", description: "Show the built-in close (X) button." },
    ],
    tokens: [
      { token: "--card", value: "bg-card", usage: "Dialog surface", swatch: true },
      { token: "--foreground", value: "text-foreground", usage: "Title", swatch: true },
      { token: "--muted-foreground", value: "text-muted-foreground", usage: "Description", swatch: true },
    ],
    a11yNote: "Always include DialogTitle (visually hidden is fine) for screen readers.",
    a11y: [
      { keys: "Tab / Shift+Tab", action: "Cycle focus (trapped)" },
      { keys: "Esc", action: "Close" },
    ],
  },
  "drawer": {
    figmaNode: "73-228",
    importCode: "import {\n  Drawer,\n  DrawerContent,\n  DrawerDescription,\n  DrawerFooter,\n  DrawerHeader,\n  DrawerTitle,\n  DrawerTrigger,\n} from \"@/components/ui/drawer\"",
    usageCode: "<Drawer>\n  <DrawerTrigger asChild>\n    <Button variant=\"outline\">Open</Button>\n  </DrawerTrigger>\n  <DrawerContent>\n    <DrawerHeader>\n      <DrawerTitle>Title</DrawerTitle>\n      <DrawerDescription>Description</DrawerDescription>\n    </DrawerHeader>\n  </DrawerContent>\n</Drawer>",
    props: [
      { component: "Drawer", prop: "open", type: "boolean", default: "—", description: "Controlled open state." },
      { component: "Drawer", prop: "direction", type: "\"top\" | \"right\" | \"bottom\" | \"left\"", default: "\"bottom\"", description: "Edge the drawer enters from." },
      { component: "Drawer", prop: "shouldScaleBackground", type: "boolean", default: "true", description: "Scale the page behind the drawer." },
    ],
    tokens: [
      { token: "--background", value: "bg-background", usage: "Drawer surface", swatch: true },
      { token: "--muted", value: "bg-muted", usage: "Drag handle", swatch: true },
    ],
    a11yNote: "Mobile-first bottom sheet built on Vaul; drag or Esc to dismiss.",
    a11y: [
      { keys: "Tab / Shift+Tab", action: "Cycle focus (trapped)" },
      { keys: "Esc", action: "Close" },
    ],
  },
  "dropdown-menu": {
    figmaNode: "73-229",
    importCode: "import {\n  DropdownMenu,\n  DropdownMenuContent,\n  DropdownMenuItem,\n  DropdownMenuLabel,\n  DropdownMenuSeparator,\n  DropdownMenuTrigger,\n} from \"@/components/ui/dropdown-menu\"",
    usageCode: "<DropdownMenu>\n  <DropdownMenuTrigger asChild>\n    <Button variant=\"outline\">Open</Button>\n  </DropdownMenuTrigger>\n  <DropdownMenuContent>\n    <DropdownMenuLabel>My Account</DropdownMenuLabel>\n    <DropdownMenuSeparator />\n    <DropdownMenuItem>Profile</DropdownMenuItem>\n    <DropdownMenuItem>Settings</DropdownMenuItem>\n  </DropdownMenuContent>\n</DropdownMenu>",
    props: [
      { component: "DropdownMenuCheckboxItem", prop: "checked", type: "boolean", default: "—", description: "Checkbox item state." },
      { component: "DropdownMenuItem", prop: "inset", type: "boolean", default: "false", description: "Indent to align with checkbox items." },
      { component: "DropdownMenuItem", prop: "disabled", type: "boolean", default: "false", description: "Disable the item." },
    ],
    tokens: [
      { token: "--popover", value: "bg-popover", usage: "Menu surface", swatch: true },
      { token: "--accent", value: "bg-accent", usage: "Highlighted item", swatch: true },
      { token: "--muted-foreground", value: "text-muted-foreground", usage: "Label / shortcut", swatch: true },
    ],
    a11yNote: "Triggered by a button; supports checkbox, radio, and submenu items.",
    a11y: [
      { keys: "↑ / ↓", action: "Move between items" },
      { keys: "→ / ←", action: "Open / close submenu" },
      { keys: "Enter / Space", action: "Select item" },
      { keys: "Esc", action: "Close menu" },
      { keys: "A–Z", action: "Type-ahead to item" },
    ],
  },
  "empty": {
    figmaNode: "1186-3809",
    importCode: "import {\n  Empty,\n  EmptyContent,\n  EmptyDescription,\n  EmptyHeader,\n  EmptyMedia,\n  EmptyTitle,\n} from \"@/components/ui/empty\"",
    usageCode: "<Empty>\n  <EmptyHeader>\n    <EmptyMedia variant=\"icon\"><Inbox /></EmptyMedia>\n    <EmptyTitle>No data yet</EmptyTitle>\n    <EmptyDescription>Add your first item to get started.</EmptyDescription>\n  </EmptyHeader>\n  <EmptyContent>\n    <Button>Add item</Button>\n  </EmptyContent>\n</Empty>",
    props: [
      { component: "EmptyMedia", prop: "variant", type: "\"default\" | \"icon\"", default: "\"default\"", description: "Media presentation." },
    ],
    tokens: [
      { token: "--muted", value: "bg-muted", usage: "Icon background", swatch: true },
      { token: "--muted-foreground", value: "text-muted-foreground", usage: "Description", swatch: true },
    ],
    a11yNote: "Layout for empty states; pair with a clear primary action.",
  },
  "field": {
    figmaNode: "1188-4205",
    importCode: "import {\n  Field,\n  FieldContent,\n  FieldDescription,\n  FieldError,\n  FieldGroup,\n  FieldLabel,\n  FieldLegend,\n  FieldSeparator,\n  FieldSet,\n} from \"@/components/ui/field\"",
    usageCode: "<FieldGroup>\n  <Field>\n    <FieldLabel htmlFor=\"email\">Email</FieldLabel>\n    <Input id=\"email\" type=\"email\" />\n    <FieldDescription>We never share it.</FieldDescription>\n  </Field>\n  <Field data-invalid>\n    <FieldLabel htmlFor=\"pw\">Password</FieldLabel>\n    <Input id=\"pw\" type=\"password\" aria-invalid />\n    <FieldError>Required</FieldError>\n  </Field>\n</FieldGroup>",
    props: [
      { component: "Field", prop: "orientation", type: "\"vertical\" | \"horizontal\" | \"responsive\"", default: "\"vertical\"", description: "Layout direction." },
      { component: "Field", prop: "data-invalid", type: "boolean", default: "—", description: "Marks the field as invalid (styles FieldError)." },
    ],
    tokens: [
      { token: "--foreground", value: "text-foreground", usage: "Label", swatch: true },
      { token: "--muted-foreground", value: "text-muted-foreground", usage: "Description", swatch: true },
      { token: "--destructive", value: "text-destructive", usage: "Error text", swatch: true },
    ],
    a11yNote: "Form-library-agnostic field scaffolding; this project uses it instead of Form. Compose with FieldSet/FieldLegend, FieldContent, FieldSeparator.",
  },
  "hover-card": {
    figmaNode: "73-231",
    importCode: "import {\n  HoverCard,\n  HoverCardContent,\n  HoverCardTrigger,\n} from \"@/components/ui/hover-card\"",
    usageCode: "<HoverCard>\n  <HoverCardTrigger asChild>\n    <Button variant=\"link\">@nextjs</Button>\n  </HoverCardTrigger>\n  <HoverCardContent>The React Framework — by Vercel.</HoverCardContent>\n</HoverCard>",
    props: [
      { component: "HoverCard", prop: "openDelay", type: "number", default: "700", description: "ms before opening on hover." },
      { component: "HoverCard", prop: "closeDelay", type: "number", default: "300", description: "ms before closing." },
    ],
    tokens: [
      { token: "--popover", value: "bg-popover", usage: "Card surface", swatch: true },
      { token: "--border", value: "border-border", usage: "Outline", swatch: true },
    ],
    a11yNote: "Hover/focus preview for sighted pointer users — don't hide essential info here.",
  },
  "input": {
    figmaNode: "73-1977",
    importCode: "import { Input } from \"@/components/ui/input\"\nimport { Label } from \"@/components/ui/label\"",
    usageCode: "<div className=\"grid gap-2\">\n  <Label htmlFor=\"email\">Email</Label>\n  <Input id=\"email\" type=\"email\" placeholder=\"name@example.com\" />\n</div>",
    props: [
      { component: "Input", prop: "type", type: "string", default: "\"text\"", description: "Native input type." },
      { component: "Input", prop: "disabled", type: "boolean", default: "false", description: "Disable the field." },
      { component: "Input", prop: "aria-invalid", type: "boolean", default: "—", description: "Apply the invalid styling + a11y state." },
    ],
    tokens: [
      { token: "--input", value: "border-input", usage: "Border", swatch: true },
      { token: "--ring", value: "ring-ring", usage: "Focus ring", swatch: true },
      { token: "--muted-foreground", value: "text-muted-foreground", usage: "Placeholder", swatch: true },
      { token: "h-9 px-3", value: "36 / 12px", usage: "Size" },
    ],
    a11yNote: "Every input needs an associated Label (htmlFor); compose with Field for description + error.",
    a11y: [
      { keys: "Tab", action: "Move focus" },
    ],
  },
  "input-group": {
    figmaNode: "1188-5363",
    importCode: "import {\n  InputGroup,\n  InputGroupAddon,\n  InputGroupButton,\n  InputGroupInput,\n  InputGroupText,\n  InputGroupTextarea,\n} from \"@/components/ui/input-group\"",
    usageCode: "<InputGroup>\n  <InputGroupAddon><Search className=\"size-4\" /></InputGroupAddon>\n  <InputGroupInput placeholder=\"Search…\" />\n</InputGroup>",
    props: [
      { component: "InputGroupAddon", prop: "align", type: "\"inline-start\" | \"inline-end\" | \"block-start\" | \"block-end\"", default: "\"inline-start\"", description: "Addon position." },
    ],
    tokens: [
      { token: "--input", value: "border-input", usage: "Group border", swatch: true },
      { token: "--muted-foreground", value: "text-muted-foreground", usage: "Addon icon", swatch: true },
    ],
    a11yNote: "Compose inputs with leading/trailing icons, text, buttons, or a spinner; supports InputGroupTextarea.",
  },
  "input-otp": {
    figmaNode: "101-698",
    importCode: "import {\n  InputOTP,\n  InputOTPGroup,\n  InputOTPSlot,\n  InputOTPSeparator,\n} from \"@/components/ui/input-otp\"",
    usageCode: "<InputOTP maxLength={6}>\n  <InputOTPGroup>\n    <InputOTPSlot index={0} />\n    <InputOTPSlot index={1} />\n    <InputOTPSlot index={2} />\n  </InputOTPGroup>\n</InputOTP>",
    props: [
      { component: "InputOTP", prop: "maxLength", type: "number", default: "—", description: "Number of slots." },
      { component: "InputOTP", prop: "pattern", type: "string", default: "—", description: "Allowed-character regex (e.g. REGEXP_ONLY_DIGITS)." },
      { component: "InputOTP", prop: "value", type: "string", default: "—", description: "Controlled value." },
      { component: "InputOTP", prop: "disabled", type: "boolean", default: "false", description: "Disable the input." },
      { component: "InputOTPSlot", prop: "index", type: "number", default: "—", description: "Slot position." },
    ],
    tokens: [
      { token: "--input", value: "border-input", usage: "Slot border", swatch: true },
      { token: "--ring", value: "ring-ring", usage: "Active slot ring", swatch: true },
    ],
    a11yNote: "Accessible one-time-password input with copy-paste support.",
    a11y: [
      { keys: "← / →", action: "Move between slots" },
      { keys: "Backspace", action: "Clear + step back" },
      { keys: "Cmd/Ctrl+V", action: "Paste full code" },
    ],
  },
  "item": {
    figmaNode: "1196-923",
    importCode: "import {\n  Item,\n  ItemContent,\n  ItemMedia,\n  ItemActions,\n  ItemTitle,\n  ItemDescription,\n} from \"@/components/ui/item\"",
    usageCode: "<Item>\n  <ItemMedia><Avatar>…</Avatar></ItemMedia>\n  <ItemContent>\n    <ItemTitle>Jane Doe</ItemTitle>\n    <ItemDescription>jane@example.com</ItemDescription>\n  </ItemContent>\n  <ItemActions><Button size=\"sm\">View</Button></ItemActions>\n</Item>",
    props: [
      { component: "Item", prop: "variant", type: "\"default\" | \"outline\" | \"muted\"", default: "\"default\"", description: "Surface style." },
    ],
    tokens: [
      { token: "--foreground", value: "text-foreground", usage: "Title", swatch: true },
      { token: "--muted-foreground", value: "text-muted-foreground", usage: "Description", swatch: true },
      { token: "--border", value: "border-border", usage: "Outline variant", swatch: true },
    ],
    a11yNote: "A flexible list row with media, content, and actions slots.",
  },
  "kbd": {
    figmaNode: "1196-1097",
    importCode: "import { Kbd, KbdGroup } from \"@/components/ui/kbd\"",
    usageCode: "<KbdGroup>\n  <Kbd>Ctrl</Kbd>\n  <Kbd>K</Kbd>\n</KbdGroup>",
    props: [
      { component: "Kbd", prop: "className", type: "string", default: "—", description: "A single keyboard key." },
      { component: "KbdGroup", prop: "className", type: "string", default: "—", description: "Groups keys into a shortcut (e.g. Ctrl + K)." },
    ],
    tokens: [
      { token: "--muted", value: "bg-muted", usage: "Key surface", swatch: true },
      { token: "--muted-foreground", value: "text-muted-foreground", usage: "Key text", swatch: true },
    ],
    a11yNote: "Presentational — displays keyboard keys and shortcuts.",
  },
  "label": {
    figmaNode: "73-1978",
    importCode: "import { Label } from \"@/components/ui/label\"",
    usageCode: "<Label htmlFor=\"email\">Your email</Label>",
    props: [
      { component: "Label", prop: "htmlFor", type: "string", default: "—", description: "Associates the label with a control id." },
    ],
    tokens: [
      { token: "--foreground", value: "text-foreground", usage: "Label text", swatch: true },
      { token: "text-sm font-medium", value: "14 / 500", usage: "Type" },
    ],
    a11yNote: "Clicking the label focuses its associated control; use FieldLabel inside a Field.",
  },
  "menubar": {
    figmaNode: "73-1979",
    importCode: "import {\n  Menubar,\n  MenubarContent,\n  MenubarItem,\n  MenubarMenu,\n  MenubarSeparator,\n  MenubarTrigger,\n} from \"@/components/ui/menubar\"",
    usageCode: "<Menubar>\n  <MenubarMenu>\n    <MenubarTrigger>File</MenubarTrigger>\n    <MenubarContent>\n      <MenubarItem>New Tab</MenubarItem>\n      <MenubarSeparator />\n      <MenubarItem>Share</MenubarItem>\n    </MenubarContent>\n  </MenubarMenu>\n</Menubar>",
    props: [
      { component: "MenubarItem", prop: "inset", type: "boolean", default: "false", description: "Indent to align with checkbox items." },
    ],
    tokens: [
      { token: "--background", value: "bg-background", usage: "Bar surface", swatch: true },
      { token: "--popover", value: "bg-popover", usage: "Menu surface", swatch: true },
      { token: "--accent", value: "bg-accent", usage: "Highlighted item", swatch: true },
    ],
    a11yNote: "Desktop-style application menu bar.",
    a11y: [
      { keys: "← / →", action: "Move between menus" },
      { keys: "↑ / ↓", action: "Move between items" },
      { keys: "→ / ←", action: "Open / close submenu" },
      { keys: "Enter / Space", action: "Select item" },
      { keys: "Esc", action: "Close menu" },
      { keys: "A–Z", action: "Type-ahead to item" },
    ],
  },
  "native-select": {
    figmaNode: "1254-65",
    importCode: "import {\n  NativeSelect,\n  NativeSelectOptGroup,\n  NativeSelectOption,\n} from \"@/components/ui/native-select\"",
    usageCode: "<NativeSelect>\n  <NativeSelectOption value=\"apple\">Apple</NativeSelectOption>\n  <NativeSelectOption value=\"banana\">Banana</NativeSelectOption>\n</NativeSelect>",
    props: [
      { component: "NativeSelect", prop: "disabled", type: "boolean", default: "false", description: "Disable the control." },
      { component: "NativeSelect", prop: "aria-invalid", type: "boolean", default: "—", description: "Apply invalid styling + a11y state." },
      { component: "NativeSelectOption", prop: "value", type: "string", default: "—", description: "Option value." },
      { component: "NativeSelectOption", prop: "disabled", type: "boolean", default: "false", description: "Disable the option." },
      { component: "NativeSelectOptGroup", prop: "label", type: "string", default: "—", description: "Group heading." },
    ],
    tokens: [
      { token: "--input", value: "border-input", usage: "Border", swatch: true },
      { token: "--ring", value: "ring-ring", usage: "Focus ring", swatch: true },
    ],
    a11yNote: "Styled wrapper over the native <select> — best for long/mobile lists; compose with Field for label + error.",
    a11y: [
      { keys: "↑ / ↓", action: "Change option (native)" },
      { keys: "Tab", action: "Move focus" },
    ],
  },
  "navigation-menu": {
    figmaNode: "73-1980",
    importCode: "import {\n  NavigationMenu,\n  NavigationMenuContent,\n  NavigationMenuItem,\n  NavigationMenuLink,\n  NavigationMenuList,\n  NavigationMenuTrigger,\n} from \"@/components/ui/navigation-menu\"",
    usageCode: "<NavigationMenu>\n  <NavigationMenuList>\n    <NavigationMenuItem>\n      <NavigationMenuTrigger>Products</NavigationMenuTrigger>\n      <NavigationMenuContent>{/* links */}</NavigationMenuContent>\n    </NavigationMenuItem>\n  </NavigationMenuList>\n</NavigationMenu>",
    props: [
      { component: "NavigationMenu", prop: "viewport", type: "boolean", default: "true", description: "Render content in a shared viewport." },
    ],
    tokens: [
      { token: "--accent", value: "bg-accent", usage: "Hover item", swatch: true },
      { token: "--popover", value: "bg-popover", usage: "Flyout surface", swatch: true },
    ],
    a11yNote: "Top-level site navigation with optional flyout panels.",
    a11y: [
      { keys: "← / →", action: "Move between top items" },
      { keys: "Enter / Space", action: "Open content" },
      { keys: "Esc", action: "Close" },
    ],
  },
  "pagination": {
    figmaNode: "73-1981",
    importCode: "import {\n  Pagination,\n  PaginationContent,\n  PaginationItem,\n  PaginationLink,\n  PaginationNext,\n  PaginationPrevious,\n} from \"@/components/ui/pagination\"",
    usageCode: "<Pagination>\n  <PaginationContent>\n    <PaginationItem><PaginationPrevious href=\"#\" /></PaginationItem>\n    <PaginationItem><PaginationLink href=\"#\" isActive>1</PaginationLink></PaginationItem>\n    <PaginationItem><PaginationNext href=\"#\" /></PaginationItem>\n  </PaginationContent>\n</Pagination>",
    props: [
      { component: "PaginationLink", prop: "isActive", type: "boolean", default: "false", description: "Marks the current page (aria-current)." },
    ],
    tokens: [
      { token: "--accent", value: "bg-accent", usage: "Active page", swatch: true },
      { token: "--foreground", value: "text-foreground", usage: "Page link", swatch: true },
    ],
    a11yNote: "Rendered as nav aria-label=\"pagination\"; the active page sets aria-current=\"page\".",
  },
  "popover": {
    figmaNode: "73-1982",
    importCode: "import {\n  Popover,\n  PopoverContent,\n  PopoverTrigger,\n} from \"@/components/ui/popover\"",
    usageCode: "<Popover>\n  <PopoverTrigger asChild>\n    <Button variant=\"outline\">Open</Button>\n  </PopoverTrigger>\n  <PopoverContent>Place content here.</PopoverContent>\n</Popover>",
    props: [
      { component: "Popover", prop: "open", type: "boolean", default: "—", description: "Controlled open state." },
      { component: "PopoverContent", prop: "align", type: "\"start\" | \"center\" | \"end\"", default: "\"center\"", description: "Alignment to the trigger." },
      { component: "PopoverContent", prop: "sideOffset", type: "number", default: "4", description: "Gap from the trigger." },
    ],
    tokens: [
      { token: "--popover", value: "bg-popover", usage: "Surface", swatch: true },
      { token: "--popover-foreground", value: "text-popover-foreground", usage: "Text", swatch: true },
      { token: "--border", value: "border-border", usage: "Outline", swatch: true },
    ],
    a11yNote: "Non-modal floating content anchored to a trigger.",
    a11y: [
      { keys: "Esc", action: "Close" },
      { keys: "Tab", action: "Move focus out" },
    ],
  },
  "progress": {
    figmaNode: "73-1983",
    importCode: "import { Progress } from \"@/components/ui/progress\"",
    usageCode: "<Progress value={60} className=\"w-full\" />",
    props: [
      { component: "Progress", prop: "value", type: "number", default: "—", description: "Completion 0–100." },
    ],
    tokens: [
      { token: "--primary", value: "bg-primary", usage: "Fill", swatch: true },
      { token: "--primary", value: "bg-primary/20", usage: "Track (20% primary)", swatch: true },
    ],
    a11yNote: "Exposes role=\"progressbar\" with aria-valuenow.",
  },
  "radio-group": {
    figmaNode: "73-1984",
    importCode: "import { RadioGroup, RadioGroupItem } from \"@/components/ui/radio-group\"\nimport { Label } from \"@/components/ui/label\"",
    usageCode: "<RadioGroup defaultValue=\"comfortable\">\n  <div className=\"flex items-center gap-2\">\n    <RadioGroupItem value=\"default\" id=\"r1\" />\n    <Label htmlFor=\"r1\">Default</Label>\n  </div>\n  <div className=\"flex items-center gap-2\">\n    <RadioGroupItem value=\"comfortable\" id=\"r2\" />\n    <Label htmlFor=\"r2\">Comfortable</Label>\n  </div>\n</RadioGroup>",
    props: [
      { component: "RadioGroup", prop: "value", type: "string", default: "—", description: "Controlled selected value." },
      { component: "RadioGroup", prop: "defaultValue", type: "string", default: "—", description: "Initial value (uncontrolled)." },
      { component: "RadioGroupItem", prop: "value", type: "string", default: "—", description: "This item's value." },
      { component: "RadioGroupItem", prop: "disabled", type: "boolean", default: "false", description: "Disable this item." },
      { component: "RadioGroupItem", prop: "aria-invalid", type: "boolean", default: "false", description: "Mark invalid for error styling." },
    ],
    tokens: [
      { token: "--primary", value: "text-primary", usage: "Selected dot", swatch: true },
      { token: "--input", value: "border-input", usage: "Ring border", swatch: true },
      { token: "--ring", value: "ring-ring", usage: "Focus ring", swatch: true },
    ],
    a11yNote: "Arrow keys move and select within the group; only one item is checked. Compose with Field for descriptions / choice cards.",
    a11y: [
      { keys: "↑ / ↓", action: "Move selection" },
      { keys: "Space", action: "Select focused" },
    ],
  },
  "scroll-area": {
    figmaNode: "73-1985",
    importCode: "import { ScrollArea } from \"@/components/ui/scroll-area\"",
    usageCode: "<ScrollArea className=\"h-72 w-48 rounded-md border p-4\">\n  {/* long content */}\n</ScrollArea>",
    props: [
      { component: "ScrollArea", prop: "type", type: "\"auto\" | \"always\" | \"scroll\" | \"hover\"", default: "\"hover\"", description: "When to show the scrollbar." },
    ],
    tokens: [
      { token: "--border", value: "border-border", usage: "Scrollbar thumb", swatch: true },
    ],
    a11yNote: "Custom-styled scrollbars over native scrolling; keyboard scroll is preserved.",
  },
  "select": {
    figmaNode: "73-1986",
    importCode: "import {\n  Select,\n  SelectContent,\n  SelectGroup,\n  SelectItem,\n  SelectLabel,\n  SelectSeparator,\n  SelectTrigger,\n  SelectValue,\n} from \"@/components/ui/select\"",
    usageCode: "<Select>\n  <SelectTrigger className=\"w-[180px]\">\n    <SelectValue placeholder=\"Theme\" />\n  </SelectTrigger>\n  <SelectContent>\n    <SelectItem value=\"light\">Light</SelectItem>\n    <SelectItem value=\"dark\">Dark</SelectItem>\n  </SelectContent>\n</Select>",
    props: [
      { component: "Select", prop: "value", type: "string", default: "—", description: "Controlled value." },
      { component: "Select", prop: "defaultValue", type: "string", default: "—", description: "Initial value (uncontrolled)." },
      { component: "SelectTrigger", prop: "aria-invalid", type: "boolean", default: "—", description: "Apply invalid styling + a11y state." },
      { component: "SelectContent", prop: "position", type: "\"item-aligned\" | \"popper\"", default: "\"item-aligned\"", description: "Dropdown alignment strategy." },
      { component: "SelectItem", prop: "value", type: "string", default: "—", description: "Option value (required)." },
      { component: "SelectItem", prop: "disabled", type: "boolean", default: "false", description: "Disable the option." },
    ],
    tokens: [
      { token: "--popover", value: "bg-popover", usage: "Menu surface", swatch: true },
      { token: "--accent", value: "bg-accent", usage: "Highlighted option", swatch: true },
      { token: "--input", value: "border-input", usage: "Trigger border", swatch: true },
    ],
    a11yNote: "Custom listbox for a known set of options; use Native Select for very long lists.",
    a11y: [
      { keys: "↑ / ↓", action: "Move between options" },
      { keys: "Enter / Space", action: "Select option" },
      { keys: "Esc", action: "Close" },
      { keys: "A–Z", action: "Type-ahead" },
    ],
  },
  "separator": {
    figmaNode: "73-1987",
    importCode: "import { Separator } from \"@/components/ui/separator\"",
    usageCode: "<Separator />\n<Separator orientation=\"vertical\" className=\"h-6\" />",
    props: [
      { component: "Separator", prop: "orientation", type: "\"horizontal\" | \"vertical\"", default: "\"horizontal\"", description: "Line direction." },
      { component: "Separator", prop: "decorative", type: "boolean", default: "true", description: "If false, exposes a semantic separator role." },
    ],
    tokens: [
      { token: "--border", value: "bg-border", usage: "Line color", swatch: true },
    ],
    a11yNote: "Decorative by default; set decorative={false} for a semantic divider.",
  },
  "sheet": {
    figmaNode: "73-1988",
    importCode: "import {\n  Sheet,\n  SheetContent,\n  SheetDescription,\n  SheetHeader,\n  SheetTitle,\n  SheetTrigger,\n} from \"@/components/ui/sheet\"",
    usageCode: "<Sheet>\n  <SheetTrigger asChild>\n    <Button variant=\"outline\">Open</Button>\n  </SheetTrigger>\n  <SheetContent side=\"right\">\n    <SheetHeader>\n      <SheetTitle>Title</SheetTitle>\n      <SheetDescription>Description</SheetDescription>\n    </SheetHeader>\n  </SheetContent>\n</Sheet>",
    props: [
      { component: "SheetContent", prop: "side", type: "\"top\" | \"right\" | \"bottom\" | \"left\"", default: "\"right\"", description: "Edge the sheet enters from." },
      { component: "SheetContent", prop: "showCloseButton", type: "boolean", default: "true", description: "Show the built-in close (X) button." },
      { component: "Sheet", prop: "open", type: "boolean", default: "—", description: "Controlled open state." },
    ],
    tokens: [
      { token: "--background", value: "bg-background", usage: "Sheet surface", swatch: true },
      { token: "--border", value: "border-border", usage: "Edge border", swatch: true },
    ],
    a11yNote: "A Dialog that slides from an edge; focus is trapped while open.",
    a11y: [
      { keys: "Tab / Shift+Tab", action: "Cycle focus (trapped)" },
      { keys: "Esc", action: "Close" },
    ],
  },
  "sidebar": {
    figmaNode: "269-32",
    importCode: "import {\n  Sidebar,\n  SidebarContent,\n  SidebarGroup,\n  SidebarMenu,\n  SidebarMenuButton,\n  SidebarMenuItem,\n  SidebarProvider,\n  SidebarTrigger,\n} from \"@/components/ui/sidebar\"",
    usageCode: "<SidebarProvider>\n  <Sidebar>\n    <SidebarContent>\n      <SidebarGroup>{/* menu */}</SidebarGroup>\n    </SidebarContent>\n  </Sidebar>\n  <main><SidebarTrigger /></main>\n</SidebarProvider>",
    props: [
      { component: "Sidebar", prop: "side", type: "\"left\" | \"right\"", default: "\"left\"", description: "Which edge it docks to." },
      { component: "Sidebar", prop: "variant", type: "\"sidebar\" | \"floating\" | \"inset\"", default: "\"sidebar\"", description: "Visual variant." },
      { component: "Sidebar", prop: "collapsible", type: "\"offcanvas\" | \"icon\" | \"none\"", default: "\"offcanvas\"", description: "Collapse behaviour." },
    ],
    tokens: [
      { token: "--sidebar", value: "bg-sidebar", usage: "Sidebar surface", swatch: true },
      { token: "--sidebar-accent", value: "bg-sidebar-accent", usage: "Active / hover item", swatch: true },
      { token: "--sidebar-border", value: "border-sidebar-border", usage: "Separators", swatch: true },
    ],
    a11yNote: "Composable app shell sidebar with its own dedicated --sidebar-* tokens.",
    a11y: [
      { keys: "Cmd/Ctrl+B", action: "Toggle sidebar" },
      { keys: "Tab", action: "Move through items" },
    ],
  },
  "skeleton": {
    figmaNode: "73-1989",
    importCode: "import { Skeleton } from \"@/components/ui/skeleton\"",
    usageCode: "<div className=\"space-y-2\">\n  <Skeleton className=\"h-4 w-[250px]\" />\n  <Skeleton className=\"h-4 w-[200px]\" />\n</div>",
    props: [
      { component: "Skeleton", prop: "className", type: "string", default: "—", description: "Set the placeholder size and shape (e.g. h-4 w-48, size-12 rounded-full)." },
    ],
    tokens: [
      { token: "--muted", value: "bg-muted", usage: "Placeholder fill", swatch: true },
      { token: "animate-pulse", value: "—", usage: "Loading animation" },
    ],
    a11yNote: "Use during loading instead of blank space; wrap with role=\"status\".",
  },
  "slider": {
    figmaNode: "73-2895",
    importCode: "import { Slider } from \"@/components/ui/slider\"",
    usageCode: "<Slider defaultValue={[50]} max={100} step={1} className=\"w-full\" />",
    props: [
      { component: "Slider", prop: "defaultValue", type: "number[]", default: "—", description: "Initial thumb value(s)." },
      { component: "Slider", prop: "max", type: "number", default: "100", description: "Maximum value." },
      { component: "Slider", prop: "step", type: "number", default: "1", description: "Step increment." },
      { component: "Slider", prop: "orientation", type: "\"horizontal\" | \"vertical\"", default: "\"horizontal\"", description: "Layout direction." },
      { component: "Slider", prop: "disabled", type: "boolean", default: "false", description: "Disable the slider." },
    ],
    tokens: [
      { token: "--primary", value: "bg-primary", usage: "Range + thumb", swatch: true },
      { token: "--muted", value: "bg-muted", usage: "Track", swatch: true },
      { token: "--ring", value: "ring-ring", usage: "Focus ring", swatch: true },
    ],
    a11yNote: "Thumb exposes role=\"slider\" with aria-valuenow.",
    a11y: [
      { keys: "← / →", action: "Adjust by step" },
      { keys: "Home / End", action: "Min / max value" },
    ],
  },
  "sonner": {
    figmaNode: "73-2896",
    importCode: "import { Toaster } from \"@/components/ui/sonner\"\nimport { toast } from \"sonner\"",
    usageCode: "// app/layout.tsx → <Toaster />\n\ntoast.success(\"Saved successfully\")\ntoast.error(\"Something went wrong\")",
    props: [
      { component: "Toaster", prop: "position", type: "\"top-center\" | \"bottom-right\" | …", default: "\"bottom-right\"", description: "Where toasts appear." },
      { component: "Toaster", prop: "richColors", type: "boolean", default: "false", description: "Tinted success/error toasts." },
    ],
    tokens: [
      { token: "--popover", value: "bg-popover", usage: "Toast surface", swatch: true },
      { token: "--border", value: "border-border", usage: "Outline", swatch: true },
    ],
    a11yNote: "The current toast system (replaces the old toast component).",
  },
  "spinner": {
    figmaNode: "1196-1174",
    importCode: "import { Spinner } from \"@/components/ui/spinner\"",
    usageCode: "<Spinner />\n<Button disabled><Spinner /> Saving…</Button>",
    props: [
      { component: "Spinner", prop: "className", type: "string", default: "—", description: "Size and color via utilities (e.g. size-6 text-primary); extends native <svg> props." },
    ],
    tokens: [
      { token: "--muted-foreground", value: "text-muted-foreground", usage: "Spinner color", swatch: true },
      { token: "animate-spin", value: "—", usage: "Rotation" },
    ],
    a11yNote: "Indeterminate loading indicator; add an accessible label nearby.",
  },
  "switch": {
    figmaNode: "73-2897",
    importCode: "import { Switch } from \"@/components/ui/switch\"\nimport { Label } from \"@/components/ui/label\"",
    usageCode: "<div className=\"flex items-center gap-2\">\n  <Switch id=\"airplane\" />\n  <Label htmlFor=\"airplane\">Airplane mode</Label>\n</div>",
    props: [
      { component: "Switch", prop: "checked", type: "boolean", default: "—", description: "Controlled on/off state." },
      { component: "Switch", prop: "onCheckedChange", type: "(checked) => void", default: "—", description: "Change handler." },
      { component: "Switch", prop: "disabled", type: "boolean", default: "false", description: "Disable the control." },
      { component: "Switch", prop: "size", type: "\"sm\" | \"default\"", default: "\"default\"", description: "Control size." },
      { component: "Switch", prop: "aria-invalid", type: "boolean", default: "false", description: "Mark invalid for error styling." },
    ],
    tokens: [
      { token: "--primary", value: "bg-primary", usage: "On track", swatch: true },
      { token: "--input", value: "bg-input", usage: "Off track", swatch: true },
      { token: "--background", value: "bg-background", usage: "Thumb", swatch: true },
    ],
    a11yNote: "Toggles immediately (no submit). Pair with a Label; compose with Field for descriptions.",
    a11y: [
      { keys: "Space / Enter", action: "Toggle state" },
    ],
  },
  "table": {
    figmaNode: "73-2898",
    importCode: "import {\n  Table,\n  TableBody,\n  TableCell,\n  TableHead,\n  TableHeader,\n  TableRow,\n} from \"@/components/ui/table\"",
    usageCode: "<Table>\n  <TableHeader>\n    <TableRow><TableHead>Name</TableHead><TableHead>Status</TableHead></TableRow>\n  </TableHeader>\n  <TableBody>\n    <TableRow><TableCell>Jane</TableCell><TableCell>Active</TableCell></TableRow>\n  </TableBody>\n</Table>",
    props: [
      { component: "Table", prop: "className", type: "string", default: "—", description: "The <table> element wrapper." },
      { component: "TableHeader", prop: "className", type: "string", default: "—", description: "The <thead> region." },
      { component: "TableBody", prop: "className", type: "string", default: "—", description: "The <tbody> region." },
      { component: "TableRow", prop: "className", type: "string", default: "—", description: "A <tr> row." },
      { component: "TableHead", prop: "className", type: "string", default: "—", description: "A header cell (<th>)." },
      { component: "TableCell", prop: "className", type: "string", default: "—", description: "A body cell (<td>)." },
      { component: "TableCaption", prop: "className", type: "string", default: "—", description: "Accessible caption describing the table." },
    ],
    tokens: [
      { token: "--border", value: "border-border", usage: "Row dividers", swatch: true },
      { token: "--muted", value: "bg-muted", usage: "Header / hover", swatch: true },
      { token: "--muted-foreground", value: "text-muted-foreground", usage: "Head text", swatch: true },
    ],
    a11yNote: "Static markup table. For sorting/filtering use the Data Table pattern.",
  },
  "tabs": {
    figmaNode: "73-2899",
    importCode: "import {\n  Tabs,\n  TabsContent,\n  TabsList,\n  TabsTrigger,\n} from \"@/components/ui/tabs\"",
    usageCode: "<Tabs defaultValue=\"account\">\n  <TabsList>\n    <TabsTrigger value=\"account\">Account</TabsTrigger>\n    <TabsTrigger value=\"password\">Password</TabsTrigger>\n  </TabsList>\n  <TabsContent value=\"account\">Account settings</TabsContent>\n  <TabsContent value=\"password\">Password settings</TabsContent>\n</Tabs>",
    props: [
      { component: "Tabs", prop: "value", type: "string", default: "—", description: "Controlled active tab." },
      { component: "Tabs", prop: "defaultValue", type: "string", default: "—", description: "Initial active tab." },
      { component: "Tabs", prop: "orientation", type: "\"horizontal\" | \"vertical\"", default: "\"horizontal\"", description: "Tab list direction." },
    ],
    tokens: [
      { token: "--muted", value: "bg-muted", usage: "Tab list track", swatch: true },
      { token: "--background", value: "bg-background", usage: "Active tab", swatch: true },
      { token: "--muted-foreground", value: "text-muted-foreground", usage: "Inactive tab", swatch: true },
    ],
    a11yNote: "Keep to ≤ 7 tabs; arrow keys move between triggers.",
    a11y: [
      { keys: "→ / ←", action: "Move between tabs" },
      { keys: "Home / End", action: "First / last tab" },
      { keys: "Enter / Space", action: "Activate tab" },
    ],
  },
  "textarea": {
    figmaNode: "73-2900",
    importCode: "import { Textarea } from \"@/components/ui/textarea\"\nimport { Label } from \"@/components/ui/label\"",
    usageCode: "<div className=\"grid gap-2\">\n  <Label htmlFor=\"msg\">Message</Label>\n  <Textarea id=\"msg\" placeholder=\"Type here…\" />\n</div>",
    props: [
      { component: "Textarea", prop: "disabled", type: "boolean", default: "false", description: "Disable the field." },
      { component: "Textarea", prop: "rows", type: "number", default: "—", description: "Visible text rows." },
      { component: "Textarea", prop: "aria-invalid", type: "boolean", default: "—", description: "Apply the invalid styling + a11y state." },
    ],
    tokens: [
      { token: "--input", value: "border-input", usage: "Border", swatch: true },
      { token: "--ring", value: "ring-ring", usage: "Focus ring", swatch: true },
      { token: "--muted-foreground", value: "text-muted-foreground", usage: "Placeholder", swatch: true },
    ],
    a11yNote: "Multi-line input; pair with a Label, or compose with Field for label + description.",
    a11y: [
      { keys: "Tab", action: "Move focus" },
    ],
  },
  "toggle": {
    figmaNode: "73-2902",
    importCode: "import { Toggle } from \"@/components/ui/toggle\"",
    usageCode: "<Toggle aria-label=\"Toggle bold\"><Bold className=\"size-4\" /></Toggle>",
    props: [
      { component: "Toggle", prop: "pressed", type: "boolean", default: "—", description: "Controlled pressed state." },
      { component: "Toggle", prop: "variant", type: "\"default\" | \"outline\"", default: "\"default\"", description: "Visual style." },
      { component: "Toggle", prop: "size", type: "\"default\" | \"sm\" | \"lg\"", default: "\"default\"", description: "Control size." },
    ],
    tokens: [
      { token: "--accent", value: "bg-accent", usage: "Pressed background", swatch: true },
      { token: "--muted-foreground", value: "text-muted-foreground", usage: "Idle icon", swatch: true },
    ],
    a11yNote: "Two-state button; icon-only toggles need an aria-label.",
    a11y: [
      { keys: "Space / Enter", action: "Toggle state" },
    ],
  },
  "toggle-group": {
    figmaNode: "73-2903",
    importCode: "import { ToggleGroup, ToggleGroupItem } from \"@/components/ui/toggle-group\"",
    usageCode: "<ToggleGroup type=\"single\" defaultValue=\"center\">\n  <ToggleGroupItem value=\"left\"><AlignLeft /></ToggleGroupItem>\n  <ToggleGroupItem value=\"center\"><AlignCenter /></ToggleGroupItem>\n  <ToggleGroupItem value=\"right\"><AlignRight /></ToggleGroupItem>\n</ToggleGroup>",
    props: [
      { component: "ToggleGroup", prop: "type", type: "\"single\" | \"multiple\"", default: "—", description: "One or many pressed items." },
      { component: "ToggleGroup", prop: "value", type: "string | string[]", default: "—", description: "Controlled value." },
      { component: "ToggleGroupItem", prop: "value", type: "string", default: "—", description: "This item's value." },
    ],
    tokens: [
      { token: "--accent", value: "bg-accent", usage: "Pressed item", swatch: true },
      { token: "--border", value: "border-border", usage: "Outline variant", swatch: true },
    ],
    a11yNote: "A set of toggles behaving as single- or multi-select.",
    a11y: [
      { keys: "← / →", action: "Move between items" },
      { keys: "Space / Enter", action: "Toggle focused item" },
    ],
  },
  "tooltip": {
    figmaNode: "73-2904",
    importCode: "import {\n  Tooltip,\n  TooltipContent,\n  TooltipProvider,\n  TooltipTrigger,\n} from \"@/components/ui/tooltip\"",
    usageCode: "<TooltipProvider>\n  <Tooltip>\n    <TooltipTrigger asChild>\n      <Button variant=\"outline\">Hover</Button>\n    </TooltipTrigger>\n    <TooltipContent>Add to library</TooltipContent>\n  </Tooltip>\n</TooltipProvider>",
    props: [
      { component: "Tooltip", prop: "delayDuration", type: "number", default: "700", description: "ms before showing on hover." },
      { component: "TooltipContent", prop: "side", type: "\"top\" | \"right\" | \"bottom\" | \"left\"", default: "\"top\"", description: "Preferred side." },
    ],
    tokens: [
      { token: "--primary", value: "bg-primary", usage: "Tooltip surface", swatch: true },
      { token: "--primary-foreground", value: "text-primary-foreground", usage: "Tooltip text", swatch: true },
    ],
    a11yNote: "Hint ≤ 10 words; never put essential or interactive content inside.",
    a11y: [
      { keys: "Tab / focus", action: "Show tooltip" },
      { keys: "Esc", action: "Dismiss" },
    ],
  },
}

export function getMeta(slug: string): ComponentMeta | undefined {
  return componentMeta[slug]
}
