// Token Sync → Variables — the WRITE side of the round-trip, done at the VARIABLE level.
//
// The shipped "WCAG Contrast Fix" plugin edits TEXT-node fills directly (and so detaches
// any variable binding). This one is different: it writes the project's design tokens
// (app/globals.css) INTO the matching Figma *Variables* via figma.variables.setValueForMode().
// The Plugin API can write Variables with no Enterprise plan and no PAT scope — unlike the
// REST endpoint (which returns 403). So this is the real "push token → Figma Variable".
//
// Matching: a Figma COLOR variable named "muted-foreground" / "Muted/Foreground" / "muted foreground"
// all normalize to "mutedforeground" and bind to the token --muted-foreground.
// Modes: a collection mode whose name contains "dark" gets the .dark value; everything else
// gets the :root (light) value.
//
// The TOKENS map below is GENERATED from app/globals.css — run `npm run figma:plugin:build`
// to refresh it after changing a token. Do not hand-edit the block between the markers.

// >>> TOKENS (generated by scripts/build-figma-plugin.mjs from app/globals.css — do not edit by hand) >>>
const TOKENS = {
  "background": {
    "light": {
      "r": 0.9799,
      "g": 0.9759,
      "b": 0.9601,
      "a": 1
    },
    "dark": {
      "r": 0.0824,
      "g": 0.0824,
      "b": 0.0776,
      "a": 1
    }
  },
  "foreground": {
    "light": {
      "r": 0.0824,
      "g": 0.0824,
      "b": 0.0776,
      "a": 1
    },
    "dark": {
      "r": 0.9799,
      "g": 0.9759,
      "b": 0.9601,
      "a": 1
    }
  },
  "card": {
    "light": {
      "r": 0.994,
      "g": 0.9924,
      "b": 0.986,
      "a": 1
    },
    "dark": {
      "r": 0.1133,
      "g": 0.1133,
      "b": 0.1067,
      "a": 1
    }
  },
  "cardforeground": {
    "light": {
      "r": 0.0824,
      "g": 0.0824,
      "b": 0.0776,
      "a": 1
    },
    "dark": {
      "r": 0.9799,
      "g": 0.9759,
      "b": 0.9601,
      "a": 1
    }
  },
  "popover": {
    "light": {
      "r": 0.994,
      "g": 0.9924,
      "b": 0.986,
      "a": 1
    },
    "dark": {
      "r": 0.1133,
      "g": 0.1133,
      "b": 0.1067,
      "a": 1
    }
  },
  "popoverforeground": {
    "light": {
      "r": 0.0824,
      "g": 0.0824,
      "b": 0.0776,
      "a": 1
    },
    "dark": {
      "r": 0.9799,
      "g": 0.9759,
      "b": 0.9601,
      "a": 1
    }
  },
  "primary": {
    "light": {
      "r": 0.852,
      "g": 0.474,
      "b": 0.348,
      "a": 1
    },
    "dark": {
      "r": 0.852,
      "g": 0.474,
      "b": 0.348,
      "a": 1
    }
  },
  "primaryforeground": {
    "light": {
      "r": 0.0824,
      "g": 0.0824,
      "b": 0.0776,
      "a": 1
    },
    "dark": {
      "r": 0.0824,
      "g": 0.0824,
      "b": 0.0776,
      "a": 1
    }
  },
  "secondary": {
    "light": {
      "r": 0.9131,
      "g": 0.9054,
      "b": 0.8669,
      "a": 1
    },
    "dark": {
      "r": 0.1664,
      "g": 0.1651,
      "b": 0.1536,
      "a": 1
    }
  },
  "secondaryforeground": {
    "light": {
      "r": 0.0824,
      "g": 0.0824,
      "b": 0.0776,
      "a": 1
    },
    "dark": {
      "r": 0.9799,
      "g": 0.9759,
      "b": 0.9601,
      "a": 1
    }
  },
  "muted": {
    "light": {
      "r": 0.9131,
      "g": 0.9054,
      "b": 0.8669,
      "a": 1
    },
    "dark": {
      "r": 0.1664,
      "g": 0.1651,
      "b": 0.1536,
      "a": 1
    }
  },
  "mutedforeground": {
    "light": {
      "r": 0.4028,
      "g": 0.3937,
      "b": 0.3572,
      "a": 1
    },
    "dark": {
      "r": 0.6931,
      "g": 0.6846,
      "b": 0.6469,
      "a": 1
    }
  },
  "accent": {
    "light": {
      "r": 0.9131,
      "g": 0.9054,
      "b": 0.8669,
      "a": 1
    },
    "dark": {
      "r": 0.1976,
      "g": 0.1961,
      "b": 0.1824,
      "a": 1
    }
  },
  "accentforeground": {
    "light": {
      "r": 0.0824,
      "g": 0.0824,
      "b": 0.0776,
      "a": 1
    },
    "dark": {
      "r": 0.9799,
      "g": 0.9759,
      "b": 0.9601,
      "a": 1
    }
  },
  "destructive": {
    "light": {
      "r": 0.8628,
      "g": 0.1572,
      "b": 0.1572,
      "a": 1
    },
    "dark": {
      "r": 0.652,
      "g": 0.148,
      "b": 0.148,
      "a": 1
    }
  },
  "border": {
    "light": {
      "r": 0.8656,
      "g": 0.8554,
      "b": 0.8144,
      "a": 1
    },
    "dark": {
      "r": 0.1976,
      "g": 0.1961,
      "b": 0.1824,
      "a": 1
    }
  },
  "input": {
    "light": {
      "r": 0.8656,
      "g": 0.8554,
      "b": 0.8144,
      "a": 1
    },
    "dark": {
      "r": 0.1976,
      "g": 0.1961,
      "b": 0.1824,
      "a": 1
    }
  },
  "ring": {
    "light": {
      "r": 0.852,
      "g": 0.474,
      "b": 0.348,
      "a": 1
    },
    "dark": {
      "r": 0.852,
      "g": 0.474,
      "b": 0.348,
      "a": 1
    }
  },
  "chart1": {
    "light": {
      "r": 0.852,
      "g": 0.474,
      "b": 0.348,
      "a": 1
    },
    "dark": {
      "r": 0.852,
      "g": 0.474,
      "b": 0.348,
      "a": 1
    }
  },
  "chart2": {
    "light": {
      "r": 0.4189,
      "g": 0.61,
      "b": 0.8011,
      "a": 1
    },
    "dark": {
      "r": 0.4189,
      "g": 0.61,
      "b": 0.8011,
      "a": 1
    }
  },
  "chart3": {
    "light": {
      "r": 0.4723,
      "g": 0.552,
      "b": 0.368,
      "a": 1
    },
    "dark": {
      "r": 0.4723,
      "g": 0.552,
      "b": 0.368,
      "a": 1
    }
  },
  "chart4": {
    "light": {
      "r": 0.6931,
      "g": 0.6846,
      "b": 0.6469,
      "a": 1
    },
    "dark": {
      "r": 0.6931,
      "g": 0.6846,
      "b": 0.6469,
      "a": 1
    }
  },
  "chart5": {
    "light": {
      "r": 0.7525,
      "g": 0.604,
      "b": 0.3475,
      "a": 1
    },
    "dark": {
      "r": 0.7525,
      "g": 0.604,
      "b": 0.3475,
      "a": 1
    }
  },
  "sidebar": {
    "light": {
      "r": 0.972,
      "g": 0.9672,
      "b": 0.948,
      "a": 1
    },
    "dark": {
      "r": 0.0618,
      "g": 0.0618,
      "b": 0.0582,
      "a": 1
    }
  },
  "sidebarforeground": {
    "light": {
      "r": 0.0824,
      "g": 0.0824,
      "b": 0.0776,
      "a": 1
    },
    "dark": {
      "r": 0.9799,
      "g": 0.9759,
      "b": 0.9601,
      "a": 1
    }
  },
  "sidebarprimary": {
    "light": {
      "r": 0.852,
      "g": 0.474,
      "b": 0.348,
      "a": 1
    },
    "dark": {
      "r": 0.852,
      "g": 0.474,
      "b": 0.348,
      "a": 1
    }
  },
  "sidebarprimaryforeground": {
    "light": {
      "r": 0.0824,
      "g": 0.0824,
      "b": 0.0776,
      "a": 1
    },
    "dark": {
      "r": 0.0824,
      "g": 0.0824,
      "b": 0.0776,
      "a": 1
    }
  },
  "sidebaraccent": {
    "light": {
      "r": 0.9131,
      "g": 0.9054,
      "b": 0.8669,
      "a": 1
    },
    "dark": {
      "r": 0.1664,
      "g": 0.1651,
      "b": 0.1536,
      "a": 1
    }
  },
  "sidebaraccentforeground": {
    "light": {
      "r": 0.0824,
      "g": 0.0824,
      "b": 0.0776,
      "a": 1
    },
    "dark": {
      "r": 0.9799,
      "g": 0.9759,
      "b": 0.9601,
      "a": 1
    }
  },
  "sidebarborder": {
    "light": {
      "r": 0.8656,
      "g": 0.8554,
      "b": 0.8144,
      "a": 1
    },
    "dark": {
      "r": 0.1976,
      "g": 0.1961,
      "b": 0.1824,
      "a": 1
    }
  },
  "sidebarring": {
    "light": {
      "r": 0.852,
      "g": 0.474,
      "b": 0.348,
      "a": 1
    },
    "dark": {
      "r": 0.852,
      "g": 0.474,
      "b": 0.348,
      "a": 1
    }
  },
  "backgroundcolor": {
    "light": {
      "r": 0,
      "g": 0,
      "b": 0,
      "a": 0.3
    },
    "dark": {
      "r": 0,
      "g": 0,
      "b": 0,
      "a": 0.5
    }
  },
  "semanticbackground": {
    "light": {
      "r": 0.477,
      "g": 0.459,
      "b": 0.423,
      "a": 1
    },
    "dark": {
      "r": 0.477,
      "g": 0.459,
      "b": 0.423,
      "a": 1
    }
  },
  "semanticborder": {
    "light": {
      "r": 0.624,
      "g": 0.608,
      "b": 0.576,
      "a": 1
    },
    "dark": {
      "r": 0.624,
      "g": 0.608,
      "b": 0.576,
      "a": 1
    }
  },
  "semanticforeground": {
    "light": {
      "r": 1,
      "g": 1,
      "b": 1,
      "a": 1
    },
    "dark": {
      "r": 1,
      "g": 1,
      "b": 1,
      "a": 1
    }
  }
};
// <<< TOKENS <<<

const norm = (s) => (s || "").toLowerCase().replace(/[^a-z0-9]/g, "");
const modeKind = (name) => ((name || "").toLowerCase().includes("dark") ? "dark" : "light");

(async () => {
  const cols = await figma.variables.getLocalVariableCollectionsAsync();
  const colById = new Map(cols.map((c) => [c.id, c]));
  const all = await figma.variables.getLocalVariablesAsync();
  const colorVars = all.filter((v) => v.resolvedType === "COLOR");

  let synced = 0;
  let modesWritten = 0;
  const unmatched = [];

  for (const v of colorVars) {
    const token = TOKENS[norm(v.name)];
    if (!token) {
      unmatched.push(v.name);
      continue;
    }
    const col = colById.get(v.variableCollectionId);
    if (!col) continue;

    let wrote = false;
    for (const m of col.modes) {
      const value = token[modeKind(m.name)] || token.light || token.dark;
      if (!value) continue;
      v.setValueForMode(m.modeId, value);
      modesWritten++;
      wrote = true;
    }
    if (wrote) synced++;
  }

  const tail = unmatched.length
    ? ` · ${unmatched.length} unmatched: ${unmatched.slice(0, 6).join(", ")}${unmatched.length > 6 ? "…" : ""}`
    : "";
  figma.closePlugin(`Token Sync — ${synced} variables / ${modesWritten} modes written${tail}`);
})();
